{{- if .Values.web.env.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.web.name }}
spec:
  encryptedData:
{{ toYaml .Values.web.env.secrets | indent 4 }}
{{- end }}

