{{- if .Values.sharedConfigs.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shared-secrets
spec:
  encryptedData:
{{ toYaml .Values.sharedConfigs.secrets | indent 4 }}
{{- end }}

