/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Authenticate and obtain a JWT
		 * @description Exchanges username/password credentials for a signed JWT.
		 *     This endpoint is the only public route; it does not require
		 *     an `Authorization` header.
		 */
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/global": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get global default configuration
		 * @description Returns the cluster-wide default configuration for all pipelines.
		 */
		get: operations["getGlobalConfig"];
		/**
		 * Update global default configuration
		 * @description Replaces the global default configuration. The body is validated
		 *     against the same rules as pipeline configuration timeouts.
		 *
		 *     A `429` is returned if any pipeline is currently in a transitioning
		 *     state (e.g. restarting); the server refuses to mutate global
		 *     configuration while a transition is in flight because the change
		 *     would be applied inconsistently across pipelines.
		 */
		put: operations["updateGlobalConfig"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/stats/summary": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get aggregated global stats summary
		 * @description Returns pre-aggregated metrics across all pipelines. The server
		 *     caches the summary for 30 seconds; on a stale or missing cache
		 *     it recomputes on demand using a singleflight lock to avoid
		 *     stampedes.
		 */
		get: operations["getStatsSummary"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/stats/history": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get historical metrics
		 * @description Returns time-series history points. Currently always returns an
		 *     empty array; the time-series requirement has been removed.
		 */
		get: operations["getStatsHistory"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pipelines": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all pipelines
		 * @description Returns a paginated, optionally filtered list of pipelines.
		 *     Query parameters:
		 *
		 *     - `search` (optional): case-insensitive substring match against
		 *       pipeline `id` and `name`.
		 *     - `status` (optional): exact-match status filter. Computed from
		 *       the pipeline's transition state and worker heartbeat.
		 *     - `page` (optional, default `1`): 1-based page index.
		 *     - `limit` (optional, default `10`): page size.
		 */
		get: operations["listPipelines"];
		put?: never;
		/**
		 * Create a new pipeline
		 * @description Creates a new pipeline configuration. The body is validated;
		 *     every referenced `source` and `sink` ID must already exist
		 *     in NATS KV or the request is rejected with `400`.
		 *
		 *     A `429` is returned if the pipeline (by `id`) is currently in
		 *     a transitioning state. The `started_at` field of the error
		 *     response carries the timestamp at which the transition started.
		 */
		post: operations["createPipeline"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pipelines/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/** Get a single pipeline */
		get: operations["getPipeline"];
		/**
		 * Update an existing pipeline
		 * @description Replaces the pipeline configuration. The path `id` overrides
		 *     any `id` in the body. Referenced sources and sinks must exist.
		 *
		 *     A `429` is returned if the pipeline is currently transitioning;
		 *     the `started_at` field carries the transition start time.
		 */
		put: operations["updatePipeline"];
		post?: never;
		/** Delete a pipeline */
		delete: operations["deletePipeline"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pipelines/{id}/status": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * Get live pipeline status and per-table stats
		 * @description Returns an aggregated view of the pipeline's runtime state:
		 *
		 *     - `status`: raw key/value snapshot of all NATS KV entries
		 *       under the pipeline's status prefix (checkpoints, per-sink
		 *       stats, transition state). Keys are NATS KV keys; values are
		 *       their deserialized JSON. Modeled as
		 *       `additionalProperties: true` because values can be any of
		 *       several worker-internal types.
		 *     - `tables`: aggregated per-table stats across all production
		 *       (non-debug) sinks.
		 *     - `sinks`: per-sink, per-table raw stats.
		 */
		get: operations["getPipelineStatus"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pipelines/{id}/restart": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Trigger a pipeline restart
		 * @description Writes a `PipelineTransitionState` entry to NATS KV to signal
		 *     the worker to reload the pipeline. The endpoint returns `202`
		 *     immediately; the actual restart is asynchronous.
		 */
		post: operations["restartPipeline"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pipelines/{id}/metrics": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * Stream pipeline metrics (Server-Sent Events)
		 * @description Opens a `text/event-stream` connection and pushes real-time
		 *     updates as the pipeline's NATS KV status keys change. The
		 *     stream is backed by a NATS KV `Watch` on the pipeline's status
		 *     prefix.
		 *
		 *     Each SSE `message` event carries a JSON object with the
		 *     changed NATS KV key, its deserialized value, the originating
		 *     `sink_id` (if applicable), and an `is_debug` flag. The exact
		 *     event payload shape is intentionally NOT part of this OpenAPI
		 *     contract — clients should treat it as opaque worker-emitted
		 *     data.
		 */
		get: operations["streamPipelineMetrics"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sources": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all source connections
		 * @description Returns all source configurations. The `pass` field is
		 *     decrypted before being returned.
		 */
		get: operations["listSources"];
		put?: never;
		/**
		 * Create a new source connection
		 * @description Creates a new source configuration. The `pass` field is
		 *     encrypted at rest by the server before being persisted to
		 *     NATS KV.
		 */
		post: operations["createSource"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sources/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * Get a single source connection
		 * @description Returns the source configuration with `pass` decrypted.
		 */
		get: operations["getSource"];
		/**
		 * Update an existing source connection
		 * @description Replaces the source configuration. The path `id` overrides
		 *     any `id` in the body. The `pass` field is encrypted at rest.
		 */
		put: operations["updateSource"];
		post?: never;
		/** Delete a source connection */
		delete: operations["deleteSource"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sources/{id}/schema": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * List available schemas for a source
		 * @description Returns the schemas discoverable on the source database. The
		 *     current implementation returns a static list; in a future
		 *     release this may trigger live discovery via a worker.
		 */
		get: operations["getSourceSchema"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sources/{id}/tables": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * List discovered tables for a source
		 * @description Returns all tables whose metadata has been discovered and
		 *     persisted by the worker. Tables are filtered to those whose
		 *     NATS KV key matches `*.sources.{id}.tables.*.metadata`.
		 */
		get: operations["listSourceTables"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sinks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all sink connections
		 * @description Returns all sink configurations. The `dsn` field is decrypted
		 *     before being returned.
		 */
		get: operations["listSinks"];
		put?: never;
		/**
		 * Create a new sink connection
		 * @description Creates a new sink configuration. The `dsn` field is encrypted
		 *     at rest by the server before being persisted to NATS KV.
		 */
		post: operations["createSink"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sinks/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * Get a single sink connection
		 * @description Returns the sink configuration with `dsn` decrypted.
		 */
		get: operations["getSink"];
		/**
		 * Update an existing sink connection
		 * @description Replaces the sink configuration. The path `id` overrides any
		 *     `id` in the body. The `dsn` field is encrypted at rest.
		 */
		put: operations["updateSink"];
		post?: never;
		/** Delete a sink connection */
		delete: operations["deleteSink"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/workers/{id}/heartbeat": {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		/**
		 * Get a worker's current heartbeat
		 * @description Returns the most recent heartbeat for the given worker ID.
		 *     Worker heartbeats are written by the worker process
		 *     (`cmd/pipeline`) and pruned by the API if older than 60
		 *     seconds. The `WorkerHeartbeat` type is a worker-internal type
		 *     and is intentionally not modeled as a reusable schema in this
		 *     spec; the response is `additionalProperties: true`.
		 */
		get: operations["getWorkerHeartbeat"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description Standard error envelope returned by all endpoints. */
		ErrorResponse: {
			/**
			 * @description Human-readable error message.
			 * @example pipeline not found
			 */
			error: string;
			/**
			 * Format: date-time
			 * @description Set only on `429` transition-state errors. Carries the
			 *     timestamp at which the in-flight transition started. The
			 *     field is omitted from the response (due to `omitempty` on
			 *     the Go struct) when no transition is active.
			 * @example 2025-01-02T15:04:05Z07:00
			 */
			started_at?: string | null;
		};
		/** @description Credentials for `/login`. Both fields are required. */
		LoginRequest: {
			/** @example admin */
			username: string;
			/**
			 * Format: password
			 * @example admin
			 */
			password: string;
		};
		/** @description Successful login response. */
		LoginResponse: {
			/**
			 * @description HS256-signed JWT (24h expiry).
			 * @example eyJhbGciOiJIUzI1NiIs...
			 */
			token: string;
		};
		/**
		 * @description User/credential record persisted in NATS KV under
		 *     `cdc.config.auth`. The `password` field is stored as a
		 *     bcrypt hash; it is not exposed via the API and is included
		 *     here only for completeness of the internal contract.
		 */
		UserConfig: {
			username: string;
			/** @description Bcrypt-hashed password. */
			password: string;
		};
		/** @description Retry policy used by both global and per-pipeline config. */
		RetryConfig: {
			/** @default 0 */
			max_retries: number;
			/**
			 * @description Initial backoff interval, e.g. "1s".
			 * @example 1s
			 */
			initial_interval?: string;
			/**
			 * @description Maximum backoff interval, e.g. "30s".
			 * @example 30s
			 */
			max_interval?: string;
			/** @default false */
			enable_dlq: boolean;
		};
		/** @description Cluster-wide default configuration applied to all pipelines. */
		GlobalConfig: {
			/** @description Default number of messages per batch. */
			batch_size: number;
			/**
			 * @description Default max time to wait before flushing a batch, e.g. "5s".
			 * @example 5s
			 */
			batch_wait: string;
			retry: components["schemas"]["RetryConfig"];
			/**
			 * @description Time given to in-flight messages to drain on shutdown, e.g. "30s".
			 * @example 30s
			 */
			drain_timeout?: string | null;
			/**
			 * @description Hard deadline for graceful shutdown, e.g. "30s".
			 * @example 30s
			 */
			shutdown_timeout?: string | null;
			/**
			 * @description Delay after a transition before considering state stable, e.g. "2s".
			 * @example 2s
			 */
			stabilization_delay?: string | null;
			/**
			 * @description Delay before restarting after a crash, e.g. "5s".
			 * @example 5s
			 */
			crash_recovery_delay?: string | null;
			/**
			 * @description Debounce delay for global config reloads, e.g. "2s".
			 * @example 2s
			 */
			global_reload_delay?: string | null;
		};
		/** @description Inline message processor configuration. */
		ProcessorConfig: {
			/** @description Unique processor name within the pipeline. */
			name: string;
			/** @description Processor type, e.g. "mask", "filter", "custom". */
			type: string;
			/** @description Free-form processor-specific options. */
			options?: {
				[key: string]: unknown;
			} | null;
			/**
			 * @description Operation types this processor applies to. The underlying
			 *     `OperationType` enum is a worker-internal type, so items
			 *     are modeled as plain strings.
			 */
			operation_types?: string[] | null;
		};
		/** @description CDC pipeline configuration. */
		PipelineConfig: {
			/** @description Unique pipeline identifier (alphanumeric). */
			id: string;
			/** @description Human-readable pipeline name. */
			name: string;
			/** @description IDs of source connections (must exist in NATS KV). */
			sources: string[];
			/** @description IDs of sink connections (must exist in NATS KV). */
			sinks: string[];
			processors?: components["schemas"]["ProcessorConfig"][] | null;
			/** @description Tables to replicate (whitelist). */
			tables: string[];
			/** @description Per-pipeline override for global batch_size. */
			batch_size?: number | null;
			/**
			 * @description Per-pipeline override for global batch_wait.
			 * @example 10s
			 */
			batch_wait?: string | null;
			/** @description Per-pipeline retry override; falls back to global. */
			retry?: components["schemas"]["RetryConfig"];
		};
		/** @description Source database connection configuration. */
		SourceConfig: {
			/** @description Unique source identifier (alphanumeric). */
			id: string;
			/**
			 * @description Source database type. Only "postgres" is supported.
			 * @enum {string}
			 */
			type: "postgres";
			/** @description Database hostname. */
			host: string;
			/** @description Database port. */
			port: number;
			/** @description Database user. */
			user?: string | null;
			/**
			 * Format: password
			 * @description Database password. On `POST`/`PUT`, the server encrypts this
			 *     value at rest before persisting to NATS KV. On `GET`, the
			 *     server decrypts it before returning.
			 */
			pass?: string | null;
			/** @description Database name. */
			database: string;
			/** @description Postgres replication slot name. */
			slot_name?: string | null;
			/** @description Postgres publication name. */
			publication_name?: string | null;
			batch_size?: number | null;
			/** @example 5s */
			batch_wait?: string | null;
			/**
			 * @description How often to re-discover tables, e.g. "30s".
			 * @example 30s
			 */
			discovery_interval?: string | null;
			snapshot_chunk_size?: number | null;
			/** @example 1s */
			snapshot_interval?: string | null;
			/** @description Schema whitelist. Empty/null means all schemas. */
			schemas?: string[] | null;
			/** @description Table whitelist within the selected schemas. */
			tables?: string[] | null;
		};
		/** @description Sink destination connection configuration. */
		SinkConfig: {
			/** @description Unique sink identifier (alphanumeric). */
			id: string;
			/**
			 * @description Sink type. `postgres_debug` sinks are excluded from
			 *     production metrics.
			 * @enum {string}
			 */
			type: "databend" | "postgres_debug";
			/**
			 * @description Data Source Name. On `POST`/`PUT`, the server encrypts this
			 *     value at rest before persisting to NATS KV. On `GET`, the
			 *     server decrypts it before returning.
			 */
			dsn: string;
			max_ack_pending?: number | null;
			/** @description Free-form sink-specific options. */
			options?: {
				[key: string]: unknown;
			} | null;
		};
		/**
		 * @description Per-table runtime statistics. Used in the `tables` and `sinks`
		 *     fields of `PipelineStatusResponse`. The Go type lives in
		 *     `internal/protocol/state.go` (a worker-internal package), but
		 *     it is part of the control-plane API contract and is therefore
		 *     modeled here.
		 */
		TableStats: {
			/** @description Per-table status, e.g. "ACTIVE", "CIRCUIT_OPEN". */
			status?: string;
			/**
			 * Format: double
			 * @description Current rows-per-second throughput.
			 */
			rps?: number;
			/**
			 * Format: int64
			 * @description Total rows successfully synchronized.
			 */
			total_synced?: number;
			/** Format: int64 */
			error_count?: number;
			/** Format: date-time */
			last_source_ts?: string;
			/** Format: date-time */
			last_processed_ts?: string;
			/**
			 * Format: int64
			 * @description Replication lag in milliseconds.
			 */
			lag_ms?: number;
			/** Format: date-time */
			updated_at?: string;
		};
		/**
		 * @description Discovered table metadata, returned by `GET /sources/{id}/tables`.
		 *     The Go type lives in `internal/protocol/state.go` but is part of
		 *     the control-plane API contract.
		 */
		TableMetadata: {
			id?: string;
			name?: string;
			columns?: string[];
			types?: string[];
			pk_columns?: string[];
		};
		/** @description Paginated pipeline list response. */
		PipelineListResponse: {
			pipelines: components["schemas"]["PipelineConfig"][];
			/**
			 * @description Total number of matching pipelines (before pagination).
			 * @example 42
			 */
			total: number;
			/**
			 * @description 1-based page index.
			 * @example 1
			 */
			page: number;
			/**
			 * @description Page size.
			 * @example 10
			 */
			limit: number;
		};
		/** @description Aggregated live status for a single pipeline. */
		PipelineStatusResponse: {
			/** @example orders-cdc */
			pipeline_id: string;
			/**
			 * @description Raw key/value snapshot of all NATS KV entries under the
			 *     pipeline's status prefix. Keys are full NATS KV keys
			 *     (e.g. `cdc.pipeline.{id}.sources.{sid}.sinks.{sinkID}.tables.{table}.stats`),
			 *     values are the deserialized worker-internal type
			 *     (`Checkpoint`, `TableStats`, or `PipelineTransitionState`).
			 *     Modeled as `additionalProperties: true` (maps to
			 *     `map[string]interface{}` in oapi-codegen).
			 */
			status: {
				[key: string]: unknown;
			};
			/** @description Aggregated per-table stats across production (non-debug) sinks. */
			tables: {
				[key: string]: components["schemas"]["TableStats"];
			};
			/** @description Per-sink, per-table raw stats. */
			sinks: {
				[key: string]: {
					[key: string]: components["schemas"]["TableStats"];
				};
			};
		};
		/** @description Response for `GET /sources`. */
		SourceListResponse: {
			sources: components["schemas"]["SourceConfig"][];
		};
		/** @description Response for `GET /sinks`. */
		SinkListResponse: {
			sinks: components["schemas"]["SinkConfig"][];
		};
		/** @description Response for `GET /sources/{id}/schema`. */
		SourceSchemaResponse: {
			/** @example prod-pg */
			source_id: string;
			/** @description Schema names discoverable on the source database. */
			available_schemas: string[];
			/**
			 * @description Current discovery status. The current implementation always
			 *     returns "ready"; future versions may report in-flight
			 *     discovery.
			 * @example ready
			 */
			discovery_status: string;
		};
		/** @description Response for `GET /sources/{id}/tables`. */
		SourceTablesResponse: {
			/** @example prod-pg */
			source_id: string;
			tables: components["schemas"]["TableMetadata"][];
		};
		/** @description Generic 202 acknowledgement for asynchronous actions. */
		AcceptedResponse: {
			/** @example restart triggered */
			status: string;
		};
	};
	responses: {
		/** @description Invalid request body or parameters */
		BadRequest: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ErrorResponse"];
			};
		};
		/** @description Missing or invalid authentication token (or bad credentials on /login) */
		Unauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ErrorResponse"];
			};
		};
		/** @description Resource not found */
		NotFound: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ErrorResponse"];
			};
		};
		/**
		 * @description A transition (restart, reload) is currently in progress for
		 *     this resource. The `started_at` field carries the transition
		 *     start timestamp when available.
		 */
		TransitionInProgress: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ErrorResponse"];
			};
		};
		/** @description Internal server error */
		InternalServerError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ErrorResponse"];
			};
		};
	};
	parameters: {
		/** @description Resource identifier (alphanumeric). */
		PathID: string;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			/** @description Authentication succeeded */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getGlobalConfig: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Global configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GlobalConfig"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
			500: components["responses"]["InternalServerError"];
		};
	};
	updateGlobalConfig: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["GlobalConfig"];
			};
		};
		responses: {
			/** @description Updated global configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GlobalConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			429: components["responses"]["TransitionInProgress"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getStatsSummary: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Aggregated stats summary */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getStatsHistory: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description History points (always empty) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					}[];
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	listPipelines: {
		parameters: {
			query?: {
				search?: string;
				status?: "Healthy" | "Transitioning" | "Error";
				page?: number;
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Paginated pipeline list */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PipelineListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	createPipeline: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PipelineConfig"];
			};
		};
		responses: {
			/** @description Pipeline created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PipelineConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			429: components["responses"]["TransitionInProgress"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getPipeline: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Pipeline configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PipelineConfig"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
			500: components["responses"]["InternalServerError"];
		};
	};
	updatePipeline: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PipelineConfig"];
			};
		};
		responses: {
			/** @description Updated pipeline configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PipelineConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			429: components["responses"]["TransitionInProgress"];
			500: components["responses"]["InternalServerError"];
		};
	};
	deletePipeline: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Pipeline deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getPipelineStatus: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Pipeline status payload */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PipelineStatusResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	restartPipeline: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Restart accepted */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AcceptedResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
			500: components["responses"]["InternalServerError"];
		};
	};
	streamPipelineMetrics: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description SSE stream of pipeline metric updates */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/event-stream": string;
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	listSources: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Source list */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SourceListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	createSource: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SourceConfig"];
			};
		};
		responses: {
			/** @description Source created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SourceConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getSource: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Source configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SourceConfig"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
			500: components["responses"]["InternalServerError"];
		};
	};
	updateSource: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SourceConfig"];
			};
		};
		responses: {
			/** @description Updated source configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SourceConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	deleteSource: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Source deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getSourceSchema: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Available schemas */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SourceSchemaResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	listSourceTables: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Discovered tables */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SourceTablesResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	listSinks: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Sink list */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SinkListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	createSink: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SinkConfig"];
			};
		};
		responses: {
			/** @description Sink created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SinkConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getSink: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Sink configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SinkConfig"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
			500: components["responses"]["InternalServerError"];
		};
	};
	updateSink: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SinkConfig"];
			};
		};
		responses: {
			/** @description Updated sink configuration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SinkConfig"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	deleteSink: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Sink deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	getWorkerHeartbeat: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Resource identifier (alphanumeric). */
				id: components["parameters"]["PathID"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Worker heartbeat */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
			500: components["responses"]["InternalServerError"];
		};
	};
}
