apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.worker.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.worker.name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
{{- with .Values.worker.env.secrets }}
spec:
  encryptedData:
{{ toYaml . | indent 4 }}
{{- end }}
