{{- if .Values.worker.env.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.worker.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.worker.name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  encryptedData:
{{ toYaml .Values.worker.env.secrets | indent 4 }}
{{- end }}

