apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.worker.name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
