export interface ProcessorConfigShape {
	/**
	 * Local-only stable identifier used as the React `key` for this row.
	 *
	 * Generated by the editor on creation (`makeDefault`) and backfilled for
	 * legacy rows that arrived from the API without one. Never sent to the
	 * backend: see `advancedConfigToPayload` which strips it before the
	 * payload is dispatched.
	 */
	id?: string;
	name: string;
	type: string;
	options?: Record<string, unknown>;
	operationTypes?: string[];
}

export const MASK_DEFAULT: ProcessorConfigShape = {
	name: "",
	type: "mask",
	operationTypes: ["insert", "update"],
	options: { fields: ["email"], salt: "" },
};

export const UPPERCASE_DEFAULT: ProcessorConfigShape = {
	name: "",
	type: "uppercase",
	operationTypes: ["insert", "update"],
	options: { column: "name" },
};

/**
 * Routes records to daya-core over NATS.
 *
 * `nats_url` and `subject` are required, and at least one of `schemas` /
 * `tables` must be set — see NewNatsProtoTransformer in
 * internal/transformer/nats/protobuf.go. `batch_size` and `pipeline_id` are
 * injected by engine/factory.go and are deliberately absent here.
 *
 * The schema/table pair below is the shape described in that file's WS-1B
 * comment: custom_objects rows (any table) OR visitations rows (any schema).
 */
export const NATS_PROTOBUF_DEFAULT: ProcessorConfigShape = {
	name: "",
	type: "nats/protobuf",
	operationTypes: ["insert", "update", "delete", "snapshot"],
	options: {
		nats_url: "nats://localhost:4222",
		subject: "",
		schemas: ["custom_objects"],
		tables: [],
	},
};

export const TEMPLATES_BY_TYPE: Record<
	string,
	readonly ProcessorConfigShape[]
> = {
	mask: [MASK_DEFAULT],
	uppercase: [UPPERCASE_DEFAULT],
	"nats/protobuf": [NATS_PROTOBUF_DEFAULT],
};
