apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdc-pipeline-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:daya-engineering/cdc-pipeline.git
    path: deploy/helm-chart
    targetRevision: main
    helm:
      version: v3
      valueFiles:
        - values.staging.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: cdc-pipeline-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
