// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NurfitraPujo/cdc-pipeline/internal/source (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination=internal/engine/mocks/engine_mocks.go -package=mocks github.com/NurfitraPujo/cdc-pipeline/internal/source Source
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	protocol "github.com/NurfitraPujo/cdc-pipeline/internal/protocol"
	source "github.com/NurfitraPujo/cdc-pipeline/internal/source"
	gomock "go.uber.org/mock/gomock"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// AlterPublication mocks base method.
func (m *MockSource) AlterPublication(ctx context.Context, tableName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlterPublication", ctx, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AlterPublication indicates an expected call of AlterPublication.
func (mr *MockSourceMockRecorder) AlterPublication(ctx, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlterPublication", reflect.TypeOf((*MockSource)(nil).AlterPublication), ctx, tableName)
}

// Name mocks base method.
func (m *MockSource) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSource)(nil).Name))
}

// Restart mocks base method.
func (m *MockSource) Restart(ctx context.Context, newTables []string) (<-chan []protocol.Message, chan<- source.SourceAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, newTables)
	ret0, _ := ret[0].(<-chan []protocol.Message)
	ret1, _ := ret[1].(chan<- source.SourceAck)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Restart indicates an expected call of Restart.
func (mr *MockSourceMockRecorder) Restart(ctx, newTables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockSource)(nil).Restart), ctx, newTables)
}

// Start mocks base method.
func (m *MockSource) Start(ctx context.Context, config protocol.SourceConfig, checkpoint protocol.Checkpoint, ackers []string) (<-chan []protocol.Message, chan<- source.SourceAck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, config, checkpoint, ackers)
	ret0, _ := ret[0].(<-chan []protocol.Message)
	ret1, _ := ret[1].(chan<- source.SourceAck)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Start indicates an expected call of Start.
func (mr *MockSourceMockRecorder) Start(ctx, config, checkpoint, ackers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSource)(nil).Start), ctx, config, checkpoint, ackers)
}

// Stop mocks base method.
func (m *MockSource) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSourceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSource)(nil).Stop))
}

// UpdateXLogPos mocks base method.
func (m *MockSource) UpdateXLogPos(ctx context.Context, lsn uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateXLogPos", ctx, lsn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateXLogPos indicates an expected call of UpdateXLogPos.
func (mr *MockSourceMockRecorder) UpdateXLogPos(ctx, lsn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateXLogPos", reflect.TypeOf((*MockSource)(nil).UpdateXLogPos), ctx, lsn)
}
