// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.com/daya-engineering/daya-data-pipeline/internal/sink (interfaces: Sink)
//
// Generated by this command:
//
//	mockgen -destination=internal/engine/mocks/sink_mocks.go -package=mocks bitbucket.com/daya-engineering/daya-data-pipeline/internal/sink Sink
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	protocol "bitbucket.com/daya-engineering/daya-data-pipeline/internal/protocol"
	gomock "go.uber.org/mock/gomock"
)

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// ApplySchema mocks base method.
func (m *MockSink) ApplySchema(ctx context.Context, schema protocol.SchemaMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySchema", ctx, schema)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySchema indicates an expected call of ApplySchema.
func (mr *MockSinkMockRecorder) ApplySchema(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySchema", reflect.TypeOf((*MockSink)(nil).ApplySchema), ctx, schema)
}

// BatchUpload mocks base method.
func (m *MockSink) BatchUpload(ctx context.Context, messages []protocol.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpload", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpload indicates an expected call of BatchUpload.
func (mr *MockSinkMockRecorder) BatchUpload(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpload", reflect.TypeOf((*MockSink)(nil).BatchUpload), ctx, messages)
}

// Name mocks base method.
func (m *MockSink) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSinkMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSink)(nil).Name))
}

// Stop mocks base method.
func (m *MockSink) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSinkMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSink)(nil).Stop))
}
