// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *GlobalConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "batch_size":
			z.BatchSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		case "retry":
			err = z.Retry.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Retry")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *GlobalConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "batch_size"
	err = en.Append(0x83, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BatchSize)
	if err != nil {
		err = msgp.WrapError(err, "BatchSize")
		return
	}
	// write "batch_wait"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.BatchWait)
	if err != nil {
		err = msgp.WrapError(err, "BatchWait")
		return
	}
	// write "retry"
	err = en.Append(0xa5, 0x72, 0x65, 0x74, 0x72, 0x79)
	if err != nil {
		return
	}
	err = z.Retry.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Retry")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *GlobalConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "batch_size"
	o = append(o, 0x83, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.BatchSize)
	// string "batch_wait"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	o = msgp.AppendDuration(o, z.BatchWait)
	// string "retry"
	o = append(o, 0xa5, 0x72, 0x65, 0x74, 0x72, 0x79)
	o, err = z.Retry.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Retry")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GlobalConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "batch_size":
			z.BatchSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		case "retry":
			bts, err = z.Retry.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Retry")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *GlobalConfig) Msgsize() (s int) {
	s = 1 + 11 + msgp.IntSize + 11 + msgp.DurationSize + 6 + z.Retry.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PipelineConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "sources":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Sources")
				return
			}
			if cap(z.Sources) >= int(zb0002) {
				z.Sources = (z.Sources)[:zb0002]
			} else {
				z.Sources = make([]string, zb0002)
			}
			for za0001 := range z.Sources {
				z.Sources[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Sources", za0001)
					return
				}
			}
		case "sinks":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Sinks")
				return
			}
			if cap(z.Sinks) >= int(zb0003) {
				z.Sinks = (z.Sinks)[:zb0003]
			} else {
				z.Sinks = make([]string, zb0003)
			}
			for za0002 := range z.Sinks {
				z.Sinks[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Sinks", za0002)
					return
				}
			}
		case "tables":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tables")
				return
			}
			if cap(z.Tables) >= int(zb0004) {
				z.Tables = (z.Tables)[:zb0004]
			} else {
				z.Tables = make([]string, zb0004)
			}
			for za0003 := range z.Tables {
				z.Tables[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tables", za0003)
					return
				}
			}
		case "batch_size":
			z.BatchSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		case "retry":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Retry")
					return
				}
				z.Retry = nil
			} else {
				if z.Retry == nil {
					z.Retry = new(RetryConfig)
				}
				err = z.Retry.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Retry")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PipelineConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "id"
	err = en.Append(0x88, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "sources"
	err = en.Append(0xa7, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Sources)))
	if err != nil {
		err = msgp.WrapError(err, "Sources")
		return
	}
	for za0001 := range z.Sources {
		err = en.WriteString(z.Sources[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Sources", za0001)
			return
		}
	}
	// write "sinks"
	err = en.Append(0xa5, 0x73, 0x69, 0x6e, 0x6b, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Sinks)))
	if err != nil {
		err = msgp.WrapError(err, "Sinks")
		return
	}
	for za0002 := range z.Sinks {
		err = en.WriteString(z.Sinks[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Sinks", za0002)
			return
		}
	}
	// write "tables"
	err = en.Append(0xa6, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tables)))
	if err != nil {
		err = msgp.WrapError(err, "Tables")
		return
	}
	for za0003 := range z.Tables {
		err = en.WriteString(z.Tables[za0003])
		if err != nil {
			err = msgp.WrapError(err, "Tables", za0003)
			return
		}
	}
	// write "batch_size"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BatchSize)
	if err != nil {
		err = msgp.WrapError(err, "BatchSize")
		return
	}
	// write "batch_wait"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.BatchWait)
	if err != nil {
		err = msgp.WrapError(err, "BatchWait")
		return
	}
	// write "retry"
	err = en.Append(0xa5, 0x72, 0x65, 0x74, 0x72, 0x79)
	if err != nil {
		return
	}
	if z.Retry == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Retry.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Retry")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PipelineConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "id"
	o = append(o, 0x88, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "sources"
	o = append(o, 0xa7, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Sources)))
	for za0001 := range z.Sources {
		o = msgp.AppendString(o, z.Sources[za0001])
	}
	// string "sinks"
	o = append(o, 0xa5, 0x73, 0x69, 0x6e, 0x6b, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Sinks)))
	for za0002 := range z.Sinks {
		o = msgp.AppendString(o, z.Sinks[za0002])
	}
	// string "tables"
	o = append(o, 0xa6, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tables)))
	for za0003 := range z.Tables {
		o = msgp.AppendString(o, z.Tables[za0003])
	}
	// string "batch_size"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.BatchSize)
	// string "batch_wait"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	o = msgp.AppendDuration(o, z.BatchWait)
	// string "retry"
	o = append(o, 0xa5, 0x72, 0x65, 0x74, 0x72, 0x79)
	if z.Retry == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Retry.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Retry")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PipelineConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "sources":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sources")
				return
			}
			if cap(z.Sources) >= int(zb0002) {
				z.Sources = (z.Sources)[:zb0002]
			} else {
				z.Sources = make([]string, zb0002)
			}
			for za0001 := range z.Sources {
				z.Sources[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Sources", za0001)
					return
				}
			}
		case "sinks":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sinks")
				return
			}
			if cap(z.Sinks) >= int(zb0003) {
				z.Sinks = (z.Sinks)[:zb0003]
			} else {
				z.Sinks = make([]string, zb0003)
			}
			for za0002 := range z.Sinks {
				z.Sinks[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Sinks", za0002)
					return
				}
			}
		case "tables":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tables")
				return
			}
			if cap(z.Tables) >= int(zb0004) {
				z.Tables = (z.Tables)[:zb0004]
			} else {
				z.Tables = make([]string, zb0004)
			}
			for za0003 := range z.Tables {
				z.Tables[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tables", za0003)
					return
				}
			}
		case "batch_size":
			z.BatchSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		case "retry":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Retry = nil
			} else {
				if z.Retry == nil {
					z.Retry = new(RetryConfig)
				}
				bts, err = z.Retry.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Retry")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PipelineConfig) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Name) + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Sources {
		s += msgp.StringPrefixSize + len(z.Sources[za0001])
	}
	s += 6 + msgp.ArrayHeaderSize
	for za0002 := range z.Sinks {
		s += msgp.StringPrefixSize + len(z.Sinks[za0002])
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0003 := range z.Tables {
		s += msgp.StringPrefixSize + len(z.Tables[za0003])
	}
	s += 11 + msgp.IntSize + 11 + msgp.DurationSize + 6
	if z.Retry == nil {
		s += msgp.NilSize
	} else {
		s += z.Retry.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RetryConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "max_retries":
			z.MaxRetries, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "MaxRetries")
				return
			}
		case "init_interval":
			z.InitialInterval, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "InitialInterval")
				return
			}
		case "max_interval":
			z.MaxInterval, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "MaxInterval")
				return
			}
		case "enable_dlq":
			z.EnableDLQ, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "EnableDLQ")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RetryConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "max_retries"
	err = en.Append(0x84, 0xab, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.MaxRetries)
	if err != nil {
		err = msgp.WrapError(err, "MaxRetries")
		return
	}
	// write "init_interval"
	err = en.Append(0xad, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.InitialInterval)
	if err != nil {
		err = msgp.WrapError(err, "InitialInterval")
		return
	}
	// write "max_interval"
	err = en.Append(0xac, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.MaxInterval)
	if err != nil {
		err = msgp.WrapError(err, "MaxInterval")
		return
	}
	// write "enable_dlq"
	err = en.Append(0xaa, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x6c, 0x71)
	if err != nil {
		return
	}
	err = en.WriteBool(z.EnableDLQ)
	if err != nil {
		err = msgp.WrapError(err, "EnableDLQ")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RetryConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "max_retries"
	o = append(o, 0x84, 0xab, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73)
	o = msgp.AppendInt(o, z.MaxRetries)
	// string "init_interval"
	o = append(o, 0xad, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	o = msgp.AppendDuration(o, z.InitialInterval)
	// string "max_interval"
	o = append(o, 0xac, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c)
	o = msgp.AppendDuration(o, z.MaxInterval)
	// string "enable_dlq"
	o = append(o, 0xaa, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x6c, 0x71)
	o = msgp.AppendBool(o, z.EnableDLQ)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RetryConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "max_retries":
			z.MaxRetries, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxRetries")
				return
			}
		case "init_interval":
			z.InitialInterval, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InitialInterval")
				return
			}
		case "max_interval":
			z.MaxInterval, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxInterval")
				return
			}
		case "enable_dlq":
			z.EnableDLQ, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EnableDLQ")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RetryConfig) Msgsize() (s int) {
	s = 1 + 12 + msgp.IntSize + 14 + msgp.DurationSize + 13 + msgp.DurationSize + 11 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SinkConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "dsn":
			z.DSN, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DSN")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z SinkConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "id"
	err = en.Append(0x83, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "type"
	err = en.Append(0xa4, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "dsn"
	err = en.Append(0xa3, 0x64, 0x73, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.DSN)
	if err != nil {
		err = msgp.WrapError(err, "DSN")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z SinkConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "id"
	o = append(o, 0x83, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "type"
	o = append(o, 0xa4, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "dsn"
	o = append(o, 0xa3, 0x64, 0x73, 0x6e)
	o = msgp.AppendString(o, z.DSN)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SinkConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "dsn":
			z.DSN, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DSN")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SinkConfig) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Type) + 4 + msgp.StringPrefixSize + len(z.DSN)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SourceConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "host":
			z.Host, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Host")
				return
			}
		case "port":
			z.Port, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "user":
			z.User, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "User")
				return
			}
		case "pass":
			z.PassEncrypted, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PassEncrypted")
				return
			}
		case "database":
			z.Database, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Database")
				return
			}
		case "slot_name":
			z.SlotName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SlotName")
				return
			}
		case "publication_name":
			z.PublicationName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PublicationName")
				return
			}
		case "batch_size":
			z.BatchSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		case "disc_int":
			z.DiscoveryInterval, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "DiscoveryInterval")
				return
			}
		case "snap_size":
			z.SnapshotChunkSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "SnapshotChunkSize")
				return
			}
		case "snap_int":
			z.SnapshotInterval, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "SnapshotInterval")
				return
			}
		case "schemas":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Schemas")
				return
			}
			if cap(z.Schemas) >= int(zb0002) {
				z.Schemas = (z.Schemas)[:zb0002]
			} else {
				z.Schemas = make([]string, zb0002)
			}
			for za0001 := range z.Schemas {
				z.Schemas[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Schemas", za0001)
					return
				}
			}
		case "tables":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tables")
				return
			}
			if cap(z.Tables) >= int(zb0003) {
				z.Tables = (z.Tables)[:zb0003]
			} else {
				z.Tables = make([]string, zb0003)
			}
			for za0002 := range z.Tables {
				z.Tables[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tables", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SourceConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 16
	// write "id"
	err = en.Append(0xde, 0x0, 0x10, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "type"
	err = en.Append(0xa4, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "host"
	err = en.Append(0xa4, 0x68, 0x6f, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Host)
	if err != nil {
		err = msgp.WrapError(err, "Host")
		return
	}
	// write "port"
	err = en.Append(0xa4, 0x70, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "user"
	err = en.Append(0xa4, 0x75, 0x73, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.User)
	if err != nil {
		err = msgp.WrapError(err, "User")
		return
	}
	// write "pass"
	err = en.Append(0xa4, 0x70, 0x61, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.PassEncrypted)
	if err != nil {
		err = msgp.WrapError(err, "PassEncrypted")
		return
	}
	// write "database"
	err = en.Append(0xa8, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Database)
	if err != nil {
		err = msgp.WrapError(err, "Database")
		return
	}
	// write "slot_name"
	err = en.Append(0xa9, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.SlotName)
	if err != nil {
		err = msgp.WrapError(err, "SlotName")
		return
	}
	// write "publication_name"
	err = en.Append(0xb0, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.PublicationName)
	if err != nil {
		err = msgp.WrapError(err, "PublicationName")
		return
	}
	// write "batch_size"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BatchSize)
	if err != nil {
		err = msgp.WrapError(err, "BatchSize")
		return
	}
	// write "batch_wait"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.BatchWait)
	if err != nil {
		err = msgp.WrapError(err, "BatchWait")
		return
	}
	// write "disc_int"
	err = en.Append(0xa8, 0x64, 0x69, 0x73, 0x63, 0x5f, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.DiscoveryInterval)
	if err != nil {
		err = msgp.WrapError(err, "DiscoveryInterval")
		return
	}
	// write "snap_size"
	err = en.Append(0xa9, 0x73, 0x6e, 0x61, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.SnapshotChunkSize)
	if err != nil {
		err = msgp.WrapError(err, "SnapshotChunkSize")
		return
	}
	// write "snap_int"
	err = en.Append(0xa8, 0x73, 0x6e, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.SnapshotInterval)
	if err != nil {
		err = msgp.WrapError(err, "SnapshotInterval")
		return
	}
	// write "schemas"
	err = en.Append(0xa7, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Schemas)))
	if err != nil {
		err = msgp.WrapError(err, "Schemas")
		return
	}
	for za0001 := range z.Schemas {
		err = en.WriteString(z.Schemas[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Schemas", za0001)
			return
		}
	}
	// write "tables"
	err = en.Append(0xa6, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tables)))
	if err != nil {
		err = msgp.WrapError(err, "Tables")
		return
	}
	for za0002 := range z.Tables {
		err = en.WriteString(z.Tables[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Tables", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SourceConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 16
	// string "id"
	o = append(o, 0xde, 0x0, 0x10, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "type"
	o = append(o, 0xa4, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "host"
	o = append(o, 0xa4, 0x68, 0x6f, 0x73, 0x74)
	o = msgp.AppendString(o, z.Host)
	// string "port"
	o = append(o, 0xa4, 0x70, 0x6f, 0x72, 0x74)
	o = msgp.AppendInt(o, z.Port)
	// string "user"
	o = append(o, 0xa4, 0x75, 0x73, 0x65, 0x72)
	o = msgp.AppendString(o, z.User)
	// string "pass"
	o = append(o, 0xa4, 0x70, 0x61, 0x73, 0x73)
	o = msgp.AppendString(o, z.PassEncrypted)
	// string "database"
	o = append(o, 0xa8, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65)
	o = msgp.AppendString(o, z.Database)
	// string "slot_name"
	o = append(o, 0xa9, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.SlotName)
	// string "publication_name"
	o = append(o, 0xb0, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.PublicationName)
	// string "batch_size"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.BatchSize)
	// string "batch_wait"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	o = msgp.AppendDuration(o, z.BatchWait)
	// string "disc_int"
	o = append(o, 0xa8, 0x64, 0x69, 0x73, 0x63, 0x5f, 0x69, 0x6e, 0x74)
	o = msgp.AppendDuration(o, z.DiscoveryInterval)
	// string "snap_size"
	o = append(o, 0xa9, 0x73, 0x6e, 0x61, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.SnapshotChunkSize)
	// string "snap_int"
	o = append(o, 0xa8, 0x73, 0x6e, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x74)
	o = msgp.AppendDuration(o, z.SnapshotInterval)
	// string "schemas"
	o = append(o, 0xa7, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Schemas)))
	for za0001 := range z.Schemas {
		o = msgp.AppendString(o, z.Schemas[za0001])
	}
	// string "tables"
	o = append(o, 0xa6, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tables)))
	for za0002 := range z.Tables {
		o = msgp.AppendString(o, z.Tables[za0002])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SourceConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "host":
			z.Host, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Host")
				return
			}
		case "port":
			z.Port, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "user":
			z.User, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "User")
				return
			}
		case "pass":
			z.PassEncrypted, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PassEncrypted")
				return
			}
		case "database":
			z.Database, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Database")
				return
			}
		case "slot_name":
			z.SlotName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SlotName")
				return
			}
		case "publication_name":
			z.PublicationName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PublicationName")
				return
			}
		case "batch_size":
			z.BatchSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		case "disc_int":
			z.DiscoveryInterval, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiscoveryInterval")
				return
			}
		case "snap_size":
			z.SnapshotChunkSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SnapshotChunkSize")
				return
			}
		case "snap_int":
			z.SnapshotInterval, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SnapshotInterval")
				return
			}
		case "schemas":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Schemas")
				return
			}
			if cap(z.Schemas) >= int(zb0002) {
				z.Schemas = (z.Schemas)[:zb0002]
			} else {
				z.Schemas = make([]string, zb0002)
			}
			for za0001 := range z.Schemas {
				z.Schemas[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Schemas", za0001)
					return
				}
			}
		case "tables":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tables")
				return
			}
			if cap(z.Tables) >= int(zb0003) {
				z.Tables = (z.Tables)[:zb0003]
			} else {
				z.Tables = make([]string, zb0003)
			}
			for za0002 := range z.Tables {
				z.Tables[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tables", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SourceConfig) Msgsize() (s int) {
	s = 3 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Type) + 5 + msgp.StringPrefixSize + len(z.Host) + 5 + msgp.IntSize + 5 + msgp.StringPrefixSize + len(z.User) + 5 + msgp.StringPrefixSize + len(z.PassEncrypted) + 9 + msgp.StringPrefixSize + len(z.Database) + 10 + msgp.StringPrefixSize + len(z.SlotName) + 17 + msgp.StringPrefixSize + len(z.PublicationName) + 11 + msgp.IntSize + 11 + msgp.DurationSize + 9 + msgp.DurationSize + 10 + msgp.IntSize + 9 + msgp.DurationSize + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Schemas {
		s += msgp.StringPrefixSize + len(z.Schemas[za0001])
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0002 := range z.Tables {
		s += msgp.StringPrefixSize + len(z.Tables[za0002])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *UserConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "username":
			z.Username, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "password":
			z.Password, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Password")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z UserConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "username"
	err = en.Append(0x82, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Username)
	if err != nil {
		err = msgp.WrapError(err, "Username")
		return
	}
	// write "password"
	err = en.Append(0xa8, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Password)
	if err != nil {
		err = msgp.WrapError(err, "Password")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z UserConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "username"
	o = append(o, 0x82, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Username)
	// string "password"
	o = append(o, 0xa8, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64)
	o = msgp.AppendString(o, z.Password)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UserConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "username":
			z.Username, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "password":
			z.Password, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Password")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z UserConfig) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.Username) + 9 + msgp.StringPrefixSize + len(z.Password)
	return
}
