// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *GlobalConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "batch_size":
			z.BatchSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z GlobalConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "batch_size"
	err = en.Append(0x82, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BatchSize)
	if err != nil {
		err = msgp.WrapError(err, "BatchSize")
		return
	}
	// write "batch_wait"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.BatchWait)
	if err != nil {
		err = msgp.WrapError(err, "BatchWait")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z GlobalConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "batch_size"
	o = append(o, 0x82, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.BatchSize)
	// string "batch_wait"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	o = msgp.AppendDuration(o, z.BatchWait)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *GlobalConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "batch_size":
			z.BatchSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z GlobalConfig) Msgsize() (s int) {
	s = 1 + 11 + msgp.IntSize + 11 + msgp.DurationSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PipelineConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "sources":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Sources")
				return
			}
			if cap(z.Sources) >= int(zb0002) {
				z.Sources = (z.Sources)[:zb0002]
			} else {
				z.Sources = make([]string, zb0002)
			}
			for za0001 := range z.Sources {
				z.Sources[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Sources", za0001)
					return
				}
			}
		case "sinks":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Sinks")
				return
			}
			if cap(z.Sinks) >= int(zb0003) {
				z.Sinks = (z.Sinks)[:zb0003]
			} else {
				z.Sinks = make([]string, zb0003)
			}
			for za0002 := range z.Sinks {
				z.Sinks[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Sinks", za0002)
					return
				}
			}
		case "tables":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tables")
				return
			}
			if cap(z.Tables) >= int(zb0004) {
				z.Tables = (z.Tables)[:zb0004]
			} else {
				z.Tables = make([]string, zb0004)
			}
			for za0003 := range z.Tables {
				z.Tables[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tables", za0003)
					return
				}
			}
		case "batch_size":
			z.BatchSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PipelineConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "id"
	err = en.Append(0x87, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "sources"
	err = en.Append(0xa7, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Sources)))
	if err != nil {
		err = msgp.WrapError(err, "Sources")
		return
	}
	for za0001 := range z.Sources {
		err = en.WriteString(z.Sources[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Sources", za0001)
			return
		}
	}
	// write "sinks"
	err = en.Append(0xa5, 0x73, 0x69, 0x6e, 0x6b, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Sinks)))
	if err != nil {
		err = msgp.WrapError(err, "Sinks")
		return
	}
	for za0002 := range z.Sinks {
		err = en.WriteString(z.Sinks[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Sinks", za0002)
			return
		}
	}
	// write "tables"
	err = en.Append(0xa6, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tables)))
	if err != nil {
		err = msgp.WrapError(err, "Tables")
		return
	}
	for za0003 := range z.Tables {
		err = en.WriteString(z.Tables[za0003])
		if err != nil {
			err = msgp.WrapError(err, "Tables", za0003)
			return
		}
	}
	// write "batch_size"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BatchSize)
	if err != nil {
		err = msgp.WrapError(err, "BatchSize")
		return
	}
	// write "batch_wait"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.BatchWait)
	if err != nil {
		err = msgp.WrapError(err, "BatchWait")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PipelineConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "id"
	o = append(o, 0x87, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "sources"
	o = append(o, 0xa7, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Sources)))
	for za0001 := range z.Sources {
		o = msgp.AppendString(o, z.Sources[za0001])
	}
	// string "sinks"
	o = append(o, 0xa5, 0x73, 0x69, 0x6e, 0x6b, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Sinks)))
	for za0002 := range z.Sinks {
		o = msgp.AppendString(o, z.Sinks[za0002])
	}
	// string "tables"
	o = append(o, 0xa6, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tables)))
	for za0003 := range z.Tables {
		o = msgp.AppendString(o, z.Tables[za0003])
	}
	// string "batch_size"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.BatchSize)
	// string "batch_wait"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x77, 0x61, 0x69, 0x74)
	o = msgp.AppendDuration(o, z.BatchWait)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PipelineConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "sources":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sources")
				return
			}
			if cap(z.Sources) >= int(zb0002) {
				z.Sources = (z.Sources)[:zb0002]
			} else {
				z.Sources = make([]string, zb0002)
			}
			for za0001 := range z.Sources {
				z.Sources[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Sources", za0001)
					return
				}
			}
		case "sinks":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sinks")
				return
			}
			if cap(z.Sinks) >= int(zb0003) {
				z.Sinks = (z.Sinks)[:zb0003]
			} else {
				z.Sinks = make([]string, zb0003)
			}
			for za0002 := range z.Sinks {
				z.Sinks[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Sinks", za0002)
					return
				}
			}
		case "tables":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tables")
				return
			}
			if cap(z.Tables) >= int(zb0004) {
				z.Tables = (z.Tables)[:zb0004]
			} else {
				z.Tables = make([]string, zb0004)
			}
			for za0003 := range z.Tables {
				z.Tables[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tables", za0003)
					return
				}
			}
		case "batch_size":
			z.BatchSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		case "batch_wait":
			z.BatchWait, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchWait")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PipelineConfig) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Name) + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Sources {
		s += msgp.StringPrefixSize + len(z.Sources[za0001])
	}
	s += 6 + msgp.ArrayHeaderSize
	for za0002 := range z.Sinks {
		s += msgp.StringPrefixSize + len(z.Sinks[za0002])
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0003 := range z.Tables {
		s += msgp.StringPrefixSize + len(z.Tables[za0003])
	}
	s += 11 + msgp.IntSize + 11 + msgp.DurationSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SourceConfig) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "host":
			z.Host, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Host")
				return
			}
		case "port":
			z.Port, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "user":
			z.User, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "User")
				return
			}
		case "pass":
			z.PassEncrypted, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PassEncrypted")
				return
			}
		case "database":
			z.Database, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Database")
				return
			}
		case "slot_name":
			z.SlotName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SlotName")
				return
			}
		case "publication_name":
			z.PublicationName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PublicationName")
				return
			}
		case "batch_size":
			z.BatchSize, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SourceConfig) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 10
	// write "id"
	err = en.Append(0x8a, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "type"
	err = en.Append(0xa4, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "host"
	err = en.Append(0xa4, 0x68, 0x6f, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Host)
	if err != nil {
		err = msgp.WrapError(err, "Host")
		return
	}
	// write "port"
	err = en.Append(0xa4, 0x70, 0x6f, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "user"
	err = en.Append(0xa4, 0x75, 0x73, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.User)
	if err != nil {
		err = msgp.WrapError(err, "User")
		return
	}
	// write "pass"
	err = en.Append(0xa4, 0x70, 0x61, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.PassEncrypted)
	if err != nil {
		err = msgp.WrapError(err, "PassEncrypted")
		return
	}
	// write "database"
	err = en.Append(0xa8, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Database)
	if err != nil {
		err = msgp.WrapError(err, "Database")
		return
	}
	// write "slot_name"
	err = en.Append(0xa9, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.SlotName)
	if err != nil {
		err = msgp.WrapError(err, "SlotName")
		return
	}
	// write "publication_name"
	err = en.Append(0xb0, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.PublicationName)
	if err != nil {
		err = msgp.WrapError(err, "PublicationName")
		return
	}
	// write "batch_size"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.BatchSize)
	if err != nil {
		err = msgp.WrapError(err, "BatchSize")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SourceConfig) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 10
	// string "id"
	o = append(o, 0x8a, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "type"
	o = append(o, 0xa4, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "host"
	o = append(o, 0xa4, 0x68, 0x6f, 0x73, 0x74)
	o = msgp.AppendString(o, z.Host)
	// string "port"
	o = append(o, 0xa4, 0x70, 0x6f, 0x72, 0x74)
	o = msgp.AppendInt(o, z.Port)
	// string "user"
	o = append(o, 0xa4, 0x75, 0x73, 0x65, 0x72)
	o = msgp.AppendString(o, z.User)
	// string "pass"
	o = append(o, 0xa4, 0x70, 0x61, 0x73, 0x73)
	o = msgp.AppendString(o, z.PassEncrypted)
	// string "database"
	o = append(o, 0xa8, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65)
	o = msgp.AppendString(o, z.Database)
	// string "slot_name"
	o = append(o, 0xa9, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.SlotName)
	// string "publication_name"
	o = append(o, 0xb0, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.PublicationName)
	// string "batch_size"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt(o, z.BatchSize)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SourceConfig) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "host":
			z.Host, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Host")
				return
			}
		case "port":
			z.Port, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "user":
			z.User, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "User")
				return
			}
		case "pass":
			z.PassEncrypted, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PassEncrypted")
				return
			}
		case "database":
			z.Database, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Database")
				return
			}
		case "slot_name":
			z.SlotName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SlotName")
				return
			}
		case "publication_name":
			z.PublicationName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PublicationName")
				return
			}
		case "batch_size":
			z.BatchSize, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchSize")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SourceConfig) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Type) + 5 + msgp.StringPrefixSize + len(z.Host) + 5 + msgp.IntSize + 5 + msgp.StringPrefixSize + len(z.User) + 5 + msgp.StringPrefixSize + len(z.PassEncrypted) + 9 + msgp.StringPrefixSize + len(z.Database) + 10 + msgp.StringPrefixSize + len(z.SlotName) + 17 + msgp.StringPrefixSize + len(z.PublicationName) + 11 + msgp.IntSize
	return
}
