// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "sid":
			z.SourceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SourceID")
				return
			}
		case "tbl":
			z.Table, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "op":
			z.Op, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
		case "lsn":
			z.LSN, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "LSN")
				return
			}
		case "pk":
			z.PK, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PK")
				return
			}
		case "pay":
			z.Payload, err = dc.ReadBytes(z.Payload)
			if err != nil {
				err = msgp.WrapError(err, "Payload")
				return
			}
		case "ts":
			z.Timestamp, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "sid"
	err = en.Append(0x87, 0xa3, 0x73, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.SourceID)
	if err != nil {
		err = msgp.WrapError(err, "SourceID")
		return
	}
	// write "tbl"
	err = en.Append(0xa3, 0x74, 0x62, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Table)
	if err != nil {
		err = msgp.WrapError(err, "Table")
		return
	}
	// write "op"
	err = en.Append(0xa2, 0x6f, 0x70)
	if err != nil {
		return
	}
	err = en.WriteString(z.Op)
	if err != nil {
		err = msgp.WrapError(err, "Op")
		return
	}
	// write "lsn"
	err = en.Append(0xa3, 0x6c, 0x73, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.LSN)
	if err != nil {
		err = msgp.WrapError(err, "LSN")
		return
	}
	// write "pk"
	err = en.Append(0xa2, 0x70, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.PK)
	if err != nil {
		err = msgp.WrapError(err, "PK")
		return
	}
	// write "pay"
	err = en.Append(0xa3, 0x70, 0x61, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Payload)
	if err != nil {
		err = msgp.WrapError(err, "Payload")
		return
	}
	// write "ts"
	err = en.Append(0xa2, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Message) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "sid"
	o = append(o, 0x87, 0xa3, 0x73, 0x69, 0x64)
	o = msgp.AppendString(o, z.SourceID)
	// string "tbl"
	o = append(o, 0xa3, 0x74, 0x62, 0x6c)
	o = msgp.AppendString(o, z.Table)
	// string "op"
	o = append(o, 0xa2, 0x6f, 0x70)
	o = msgp.AppendString(o, z.Op)
	// string "lsn"
	o = append(o, 0xa3, 0x6c, 0x73, 0x6e)
	o = msgp.AppendUint64(o, z.LSN)
	// string "pk"
	o = append(o, 0xa2, 0x70, 0x6b)
	o = msgp.AppendString(o, z.PK)
	// string "pay"
	o = append(o, 0xa3, 0x70, 0x61, 0x79)
	o = msgp.AppendBytes(o, z.Payload)
	// string "ts"
	o = append(o, 0xa2, 0x74, 0x73)
	o = msgp.AppendTime(o, z.Timestamp)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Message) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "sid":
			z.SourceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceID")
				return
			}
		case "tbl":
			z.Table, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "op":
			z.Op, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
		case "lsn":
			z.LSN, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LSN")
				return
			}
		case "pk":
			z.PK, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PK")
				return
			}
		case "pay":
			z.Payload, bts, err = msgp.ReadBytesBytes(bts, z.Payload)
			if err != nil {
				err = msgp.WrapError(err, "Payload")
				return
			}
		case "ts":
			z.Timestamp, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Message) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.SourceID) + 4 + msgp.StringPrefixSize + len(z.Table) + 3 + msgp.StringPrefixSize + len(z.Op) + 4 + msgp.Uint64Size + 3 + msgp.StringPrefixSize + len(z.PK) + 4 + msgp.BytesPrefixSize + len(z.Payload) + 3 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageBatch) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(MessageBatch, zb0002)
	}
	for zb0001 := range *z {
		err = (*z)[zb0001].DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MessageBatch) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		err = z[zb0003].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MessageBatch) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		o, err = z[zb0003].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageBatch) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(MessageBatch, zb0002)
	}
	for zb0001 := range *z {
		bts, err = (*z)[zb0001].UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MessageBatch) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		s += z[zb0003].Msgsize()
	}
	return
}
