// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "sid":
			z.SourceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SourceID")
				return
			}
		case "tbl":
			z.Table, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "op":
			z.Op, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
		case "lsn":
			z.LSN, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "LSN")
				return
			}
		case "pk":
			z.PK, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PK")
				return
			}
		case "uuid":
			z.UUID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UUID")
				return
			}
		case "pay":
			z.Payload, err = dc.ReadBytes(z.Payload)
			if err != nil {
				err = msgp.WrapError(err, "Payload")
				return
			}
		case "ts":
			z.Timestamp, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "meta":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Schema")
					return
				}
				z.Schema = nil
			} else {
				if z.Schema == nil {
					z.Schema = new(SchemaMetadata)
				}
				err = z.Schema.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Schema")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	_ = zb0001Mask
	if z.Schema == nil {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "sid"
		err = en.Append(0xa3, 0x73, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.SourceID)
		if err != nil {
			err = msgp.WrapError(err, "SourceID")
			return
		}
		// write "tbl"
		err = en.Append(0xa3, 0x74, 0x62, 0x6c)
		if err != nil {
			return
		}
		err = en.WriteString(z.Table)
		if err != nil {
			err = msgp.WrapError(err, "Table")
			return
		}
		// write "op"
		err = en.Append(0xa2, 0x6f, 0x70)
		if err != nil {
			return
		}
		err = en.WriteString(z.Op)
		if err != nil {
			err = msgp.WrapError(err, "Op")
			return
		}
		// write "lsn"
		err = en.Append(0xa3, 0x6c, 0x73, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteUint64(z.LSN)
		if err != nil {
			err = msgp.WrapError(err, "LSN")
			return
		}
		// write "pk"
		err = en.Append(0xa2, 0x70, 0x6b)
		if err != nil {
			return
		}
		err = en.WriteString(z.PK)
		if err != nil {
			err = msgp.WrapError(err, "PK")
			return
		}
		// write "uuid"
		err = en.Append(0xa4, 0x75, 0x75, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.UUID)
		if err != nil {
			err = msgp.WrapError(err, "UUID")
			return
		}
		// write "pay"
		err = en.Append(0xa3, 0x70, 0x61, 0x79)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.Payload)
		if err != nil {
			err = msgp.WrapError(err, "Payload")
			return
		}
		// write "ts"
		err = en.Append(0xa2, 0x74, 0x73)
		if err != nil {
			return
		}
		err = en.WriteTime(z.Timestamp)
		if err != nil {
			err = msgp.WrapError(err, "Timestamp")
			return
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "meta"
			err = en.Append(0xa4, 0x6d, 0x65, 0x74, 0x61)
			if err != nil {
				return
			}
			if z.Schema == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.Schema.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "Schema")
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Message) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	_ = zb0001Mask
	if z.Schema == nil {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "sid"
		o = append(o, 0xa3, 0x73, 0x69, 0x64)
		o = msgp.AppendString(o, z.SourceID)
		// string "tbl"
		o = append(o, 0xa3, 0x74, 0x62, 0x6c)
		o = msgp.AppendString(o, z.Table)
		// string "op"
		o = append(o, 0xa2, 0x6f, 0x70)
		o = msgp.AppendString(o, z.Op)
		// string "lsn"
		o = append(o, 0xa3, 0x6c, 0x73, 0x6e)
		o = msgp.AppendUint64(o, z.LSN)
		// string "pk"
		o = append(o, 0xa2, 0x70, 0x6b)
		o = msgp.AppendString(o, z.PK)
		// string "uuid"
		o = append(o, 0xa4, 0x75, 0x75, 0x69, 0x64)
		o = msgp.AppendString(o, z.UUID)
		// string "pay"
		o = append(o, 0xa3, 0x70, 0x61, 0x79)
		o = msgp.AppendBytes(o, z.Payload)
		// string "ts"
		o = append(o, 0xa2, 0x74, 0x73)
		o = msgp.AppendTime(o, z.Timestamp)
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "meta"
			o = append(o, 0xa4, 0x6d, 0x65, 0x74, 0x61)
			if z.Schema == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.Schema.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "Schema")
					return
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Message) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "sid":
			z.SourceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceID")
				return
			}
		case "tbl":
			z.Table, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "op":
			z.Op, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
		case "lsn":
			z.LSN, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LSN")
				return
			}
		case "pk":
			z.PK, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PK")
				return
			}
		case "uuid":
			z.UUID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UUID")
				return
			}
		case "pay":
			z.Payload, bts, err = msgp.ReadBytesBytes(bts, z.Payload)
			if err != nil {
				err = msgp.WrapError(err, "Payload")
				return
			}
		case "ts":
			z.Timestamp, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "meta":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Schema = nil
			} else {
				if z.Schema == nil {
					z.Schema = new(SchemaMetadata)
				}
				bts, err = z.Schema.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Schema")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Message) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.SourceID) + 4 + msgp.StringPrefixSize + len(z.Table) + 3 + msgp.StringPrefixSize + len(z.Op) + 4 + msgp.Uint64Size + 3 + msgp.StringPrefixSize + len(z.PK) + 5 + msgp.StringPrefixSize + len(z.UUID) + 4 + msgp.BytesPrefixSize + len(z.Payload) + 3 + msgp.TimeSize + 5
	if z.Schema == nil {
		s += msgp.NilSize
	} else {
		s += z.Schema.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageBatch) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(MessageBatch, zb0002)
	}
	for zb0001 := range *z {
		err = (*z)[zb0001].DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MessageBatch) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		err = z[zb0003].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MessageBatch) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		o, err = z[zb0003].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageBatch) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(MessageBatch, zb0002)
	}
	for zb0001 := range *z {
		bts, err = (*z)[zb0001].UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MessageBatch) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		s += z[zb0003].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SchemaMetadata) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "tbl":
			z.Table, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "sch":
			z.Schema, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Schema")
				return
			}
		case "cols":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if z.Columns == nil {
				z.Columns = make(map[string]string, zb0002)
			} else if len(z.Columns) > 0 {
				clear(z.Columns)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Columns")
					return
				}
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
				z.Columns[za0001] = za0002
			}
		case "pks":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PKColumns")
				return
			}
			if cap(z.PKColumns) >= int(zb0003) {
				z.PKColumns = (z.PKColumns)[:zb0003]
			} else {
				z.PKColumns = make([]string, zb0003)
			}
			for za0003 := range z.PKColumns {
				z.PKColumns[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "PKColumns", za0003)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SchemaMetadata) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "tbl"
	err = en.Append(0x84, 0xa3, 0x74, 0x62, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Table)
	if err != nil {
		err = msgp.WrapError(err, "Table")
		return
	}
	// write "sch"
	err = en.Append(0xa3, 0x73, 0x63, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Schema)
	if err != nil {
		err = msgp.WrapError(err, "Schema")
		return
	}
	// write "cols"
	err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Columns)))
	if err != nil {
		err = msgp.WrapError(err, "Columns")
		return
	}
	for za0001, za0002 := range z.Columns {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Columns")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Columns", za0001)
			return
		}
	}
	// write "pks"
	err = en.Append(0xa3, 0x70, 0x6b, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.PKColumns)))
	if err != nil {
		err = msgp.WrapError(err, "PKColumns")
		return
	}
	for za0003 := range z.PKColumns {
		err = en.WriteString(z.PKColumns[za0003])
		if err != nil {
			err = msgp.WrapError(err, "PKColumns", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SchemaMetadata) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "tbl"
	o = append(o, 0x84, 0xa3, 0x74, 0x62, 0x6c)
	o = msgp.AppendString(o, z.Table)
	// string "sch"
	o = append(o, 0xa3, 0x73, 0x63, 0x68)
	o = msgp.AppendString(o, z.Schema)
	// string "cols"
	o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Columns)))
	for za0001, za0002 := range z.Columns {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	// string "pks"
	o = append(o, 0xa3, 0x70, 0x6b, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.PKColumns)))
	for za0003 := range z.PKColumns {
		o = msgp.AppendString(o, z.PKColumns[za0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SchemaMetadata) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "tbl":
			z.Table, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Table")
				return
			}
		case "sch":
			z.Schema, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Schema")
				return
			}
		case "cols":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if z.Columns == nil {
				z.Columns = make(map[string]string, zb0002)
			} else if len(z.Columns) > 0 {
				clear(z.Columns)
			}
			for zb0002 > 0 {
				var za0002 string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Columns")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
				z.Columns[za0001] = za0002
			}
		case "pks":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PKColumns")
				return
			}
			if cap(z.PKColumns) >= int(zb0003) {
				z.PKColumns = (z.PKColumns)[:zb0003]
			} else {
				z.PKColumns = make([]string, zb0003)
			}
			for za0003 := range z.PKColumns {
				z.PKColumns[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PKColumns", za0003)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SchemaMetadata) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Table) + 4 + msgp.StringPrefixSize + len(z.Schema) + 5 + msgp.MapHeaderSize
	if z.Columns != nil {
		for za0001, za0002 := range z.Columns {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	s += 4 + msgp.ArrayHeaderSize
	for za0003 := range z.PKColumns {
		s += msgp.StringPrefixSize + len(z.PKColumns[za0003])
	}
	return
}
