// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Checkpoint) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "i_lsn":
			z.IngressLSN, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "IngressLSN")
				return
			}
		case "e_lsn":
			z.EgressLSN, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "EgressLSN")
				return
			}
		case "l_pk":
			z.LastPK, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "LastPK")
				return
			}
		case "status":
			z.Status, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "updated":
			z.UpdatedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Checkpoint) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "i_lsn"
	err = en.Append(0x85, 0xa5, 0x69, 0x5f, 0x6c, 0x73, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.IngressLSN)
	if err != nil {
		err = msgp.WrapError(err, "IngressLSN")
		return
	}
	// write "e_lsn"
	err = en.Append(0xa5, 0x65, 0x5f, 0x6c, 0x73, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.EgressLSN)
	if err != nil {
		err = msgp.WrapError(err, "EgressLSN")
		return
	}
	// write "l_pk"
	err = en.Append(0xa4, 0x6c, 0x5f, 0x70, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.LastPK)
	if err != nil {
		err = msgp.WrapError(err, "LastPK")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "updated"
	err = en.Append(0xa7, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Checkpoint) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "i_lsn"
	o = append(o, 0x85, 0xa5, 0x69, 0x5f, 0x6c, 0x73, 0x6e)
	o = msgp.AppendUint64(o, z.IngressLSN)
	// string "e_lsn"
	o = append(o, 0xa5, 0x65, 0x5f, 0x6c, 0x73, 0x6e)
	o = msgp.AppendUint64(o, z.EgressLSN)
	// string "l_pk"
	o = append(o, 0xa4, 0x6c, 0x5f, 0x70, 0x6b)
	o = msgp.AppendString(o, z.LastPK)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendString(o, z.Status)
	// string "updated"
	o = append(o, 0xa7, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64)
	o = msgp.AppendTime(o, z.UpdatedAt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Checkpoint) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "i_lsn":
			z.IngressLSN, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IngressLSN")
				return
			}
		case "e_lsn":
			z.EgressLSN, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EgressLSN")
				return
			}
		case "l_pk":
			z.LastPK, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastPK")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "updated":
			z.UpdatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Checkpoint) Msgsize() (s int) {
	s = 1 + 6 + msgp.Uint64Size + 6 + msgp.Uint64Size + 5 + msgp.StringPrefixSize + len(z.LastPK) + 7 + msgp.StringPrefixSize + len(z.Status) + 8 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PipelineTransitionState) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "status":
			z.Status, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "started":
			z.StartedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "StartedAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z PipelineTransitionState) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "id"
	err = en.Append(0x83, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "started"
	err = en.Append(0xa7, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteTime(z.StartedAt)
	if err != nil {
		err = msgp.WrapError(err, "StartedAt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z PipelineTransitionState) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "id"
	o = append(o, 0x83, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendString(o, z.Status)
	// string "started"
	o = append(o, 0xa7, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64)
	o = msgp.AppendTime(o, z.StartedAt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PipelineTransitionState) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "started":
			z.StartedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StartedAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z PipelineTransitionState) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 7 + msgp.StringPrefixSize + len(z.Status) + 8 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TableMetadata) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "cols":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if cap(z.Columns) >= int(zb0002) {
				z.Columns = (z.Columns)[:zb0002]
			} else {
				z.Columns = make([]string, zb0002)
			}
			for za0001 := range z.Columns {
				z.Columns[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
			}
		case "types":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Types")
				return
			}
			if cap(z.Types) >= int(zb0003) {
				z.Types = (z.Types)[:zb0003]
			} else {
				z.Types = make([]string, zb0003)
			}
			for za0002 := range z.Types {
				z.Types[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Types", za0002)
					return
				}
			}
		case "pk":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PKColumns")
				return
			}
			if cap(z.PKColumns) >= int(zb0004) {
				z.PKColumns = (z.PKColumns)[:zb0004]
			} else {
				z.PKColumns = make([]string, zb0004)
			}
			for za0003 := range z.PKColumns {
				z.PKColumns[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "PKColumns", za0003)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TableMetadata) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "id"
	err = en.Append(0x85, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "cols"
	err = en.Append(0xa4, 0x63, 0x6f, 0x6c, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Columns)))
	if err != nil {
		err = msgp.WrapError(err, "Columns")
		return
	}
	for za0001 := range z.Columns {
		err = en.WriteString(z.Columns[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Columns", za0001)
			return
		}
	}
	// write "types"
	err = en.Append(0xa5, 0x74, 0x79, 0x70, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Types)))
	if err != nil {
		err = msgp.WrapError(err, "Types")
		return
	}
	for za0002 := range z.Types {
		err = en.WriteString(z.Types[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Types", za0002)
			return
		}
	}
	// write "pk"
	err = en.Append(0xa2, 0x70, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.PKColumns)))
	if err != nil {
		err = msgp.WrapError(err, "PKColumns")
		return
	}
	for za0003 := range z.PKColumns {
		err = en.WriteString(z.PKColumns[za0003])
		if err != nil {
			err = msgp.WrapError(err, "PKColumns", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TableMetadata) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "id"
	o = append(o, 0x85, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.ID)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "cols"
	o = append(o, 0xa4, 0x63, 0x6f, 0x6c, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Columns)))
	for za0001 := range z.Columns {
		o = msgp.AppendString(o, z.Columns[za0001])
	}
	// string "types"
	o = append(o, 0xa5, 0x74, 0x79, 0x70, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Types)))
	for za0002 := range z.Types {
		o = msgp.AppendString(o, z.Types[za0002])
	}
	// string "pk"
	o = append(o, 0xa2, 0x70, 0x6b)
	o = msgp.AppendArrayHeader(o, uint32(len(z.PKColumns)))
	for za0003 := range z.PKColumns {
		o = msgp.AppendString(o, z.PKColumns[za0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TableMetadata) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "cols":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if cap(z.Columns) >= int(zb0002) {
				z.Columns = (z.Columns)[:zb0002]
			} else {
				z.Columns = make([]string, zb0002)
			}
			for za0001 := range z.Columns {
				z.Columns[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
			}
		case "types":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Types")
				return
			}
			if cap(z.Types) >= int(zb0003) {
				z.Types = (z.Types)[:zb0003]
			} else {
				z.Types = make([]string, zb0003)
			}
			for za0002 := range z.Types {
				z.Types[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Types", za0002)
					return
				}
			}
		case "pk":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PKColumns")
				return
			}
			if cap(z.PKColumns) >= int(zb0004) {
				z.PKColumns = (z.PKColumns)[:zb0004]
			} else {
				z.PKColumns = make([]string, zb0004)
			}
			for za0003 := range z.PKColumns {
				z.PKColumns[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PKColumns", za0003)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TableMetadata) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 5 + msgp.StringPrefixSize + len(z.Name) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Columns {
		s += msgp.StringPrefixSize + len(z.Columns[za0001])
	}
	s += 6 + msgp.ArrayHeaderSize
	for za0002 := range z.Types {
		s += msgp.StringPrefixSize + len(z.Types[za0002])
	}
	s += 3 + msgp.ArrayHeaderSize
	for za0003 := range z.PKColumns {
		s += msgp.StringPrefixSize + len(z.PKColumns[za0003])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TableStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "rps":
			z.RPS, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "RPS")
				return
			}
		case "total":
			z.TotalSynced, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalSynced")
				return
			}
		case "errs":
			z.ErrorCount, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ErrorCount")
				return
			}
		case "src_ts":
			z.LastSourceTS, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "LastSourceTS")
				return
			}
		case "proc_ts":
			z.LastProcessedTS, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "LastProcessedTS")
				return
			}
		case "lag":
			z.LagMS, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "LagMS")
				return
			}
		case "upd":
			z.UpdatedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TableStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "rps"
	err = en.Append(0x87, 0xa3, 0x72, 0x70, 0x73)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.RPS)
	if err != nil {
		err = msgp.WrapError(err, "RPS")
		return
	}
	// write "total"
	err = en.Append(0xa5, 0x74, 0x6f, 0x74, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.TotalSynced)
	if err != nil {
		err = msgp.WrapError(err, "TotalSynced")
		return
	}
	// write "errs"
	err = en.Append(0xa4, 0x65, 0x72, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ErrorCount)
	if err != nil {
		err = msgp.WrapError(err, "ErrorCount")
		return
	}
	// write "src_ts"
	err = en.Append(0xa6, 0x73, 0x72, 0x63, 0x5f, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteTime(z.LastSourceTS)
	if err != nil {
		err = msgp.WrapError(err, "LastSourceTS")
		return
	}
	// write "proc_ts"
	err = en.Append(0xa7, 0x70, 0x72, 0x6f, 0x63, 0x5f, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteTime(z.LastProcessedTS)
	if err != nil {
		err = msgp.WrapError(err, "LastProcessedTS")
		return
	}
	// write "lag"
	err = en.Append(0xa3, 0x6c, 0x61, 0x67)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.LagMS)
	if err != nil {
		err = msgp.WrapError(err, "LagMS")
		return
	}
	// write "upd"
	err = en.Append(0xa3, 0x75, 0x70, 0x64)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TableStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "rps"
	o = append(o, 0x87, 0xa3, 0x72, 0x70, 0x73)
	o = msgp.AppendFloat64(o, z.RPS)
	// string "total"
	o = append(o, 0xa5, 0x74, 0x6f, 0x74, 0x61, 0x6c)
	o = msgp.AppendUint64(o, z.TotalSynced)
	// string "errs"
	o = append(o, 0xa4, 0x65, 0x72, 0x72, 0x73)
	o = msgp.AppendUint64(o, z.ErrorCount)
	// string "src_ts"
	o = append(o, 0xa6, 0x73, 0x72, 0x63, 0x5f, 0x74, 0x73)
	o = msgp.AppendTime(o, z.LastSourceTS)
	// string "proc_ts"
	o = append(o, 0xa7, 0x70, 0x72, 0x6f, 0x63, 0x5f, 0x74, 0x73)
	o = msgp.AppendTime(o, z.LastProcessedTS)
	// string "lag"
	o = append(o, 0xa3, 0x6c, 0x61, 0x67)
	o = msgp.AppendInt64(o, z.LagMS)
	// string "upd"
	o = append(o, 0xa3, 0x75, 0x70, 0x64)
	o = msgp.AppendTime(o, z.UpdatedAt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TableStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "rps":
			z.RPS, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RPS")
				return
			}
		case "total":
			z.TotalSynced, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalSynced")
				return
			}
		case "errs":
			z.ErrorCount, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ErrorCount")
				return
			}
		case "src_ts":
			z.LastSourceTS, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastSourceTS")
				return
			}
		case "proc_ts":
			z.LastProcessedTS, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastProcessedTS")
				return
			}
		case "lag":
			z.LagMS, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LagMS")
				return
			}
		case "upd":
			z.UpdatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TableStats) Msgsize() (s int) {
	s = 1 + 4 + msgp.Float64Size + 6 + msgp.Uint64Size + 5 + msgp.Uint64Size + 7 + msgp.TimeSize + 8 + msgp.TimeSize + 4 + msgp.Int64Size + 4 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *WorkerHeartbeat) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.WorkerID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "WorkerID")
				return
			}
		case "status":
			z.Status, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "uptime":
			z.UptimeSec, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UptimeSec")
				return
			}
		case "upd":
			z.UpdatedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *WorkerHeartbeat) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "id"
	err = en.Append(0x84, 0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.WorkerID)
	if err != nil {
		err = msgp.WrapError(err, "WorkerID")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "uptime"
	err = en.Append(0xa6, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UptimeSec)
	if err != nil {
		err = msgp.WrapError(err, "UptimeSec")
		return
	}
	// write "upd"
	err = en.Append(0xa3, 0x75, 0x70, 0x64)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdatedAt)
	if err != nil {
		err = msgp.WrapError(err, "UpdatedAt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *WorkerHeartbeat) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "id"
	o = append(o, 0x84, 0xa2, 0x69, 0x64)
	o = msgp.AppendString(o, z.WorkerID)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendString(o, z.Status)
	// string "uptime"
	o = append(o, 0xa6, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.UptimeSec)
	// string "upd"
	o = append(o, 0xa3, 0x75, 0x70, 0x64)
	o = msgp.AppendTime(o, z.UpdatedAt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *WorkerHeartbeat) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.WorkerID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WorkerID")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "uptime":
			z.UptimeSec, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UptimeSec")
				return
			}
		case "upd":
			z.UpdatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdatedAt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *WorkerHeartbeat) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.WorkerID) + 7 + msgp.StringPrefixSize + len(z.Status) + 7 + msgp.Int64Size + 4 + msgp.TimeSize
	return
}
