/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as SinksIndexRouteImport } from './routes/sinks/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines/index'
import { Route as PipelinesCreateRouteImport } from './routes/pipelines/create'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as PipelinesIdIndexRouteImport } from './routes/pipelines/$id/index'
import { Route as PipelinesIdEditRouteImport } from './routes/pipelines/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SinksIndexRoute = SinksIndexRouteImport.update({
  id: '/sinks/',
  path: '/sinks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesCreateRoute = PipelinesCreateRouteImport.update({
  id: '/pipelines/create',
  path: '/pipelines/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIdIndexRoute = PipelinesIdIndexRouteImport.update({
  id: '/pipelines/$id/',
  path: '/pipelines/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIdEditRoute = PipelinesIdEditRouteImport.update({
  id: '/pipelines/$id/edit',
  path: '/pipelines/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pipelines/create': typeof PipelinesCreateRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/sinks/': typeof SinksIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/pipelines/$id/edit': typeof PipelinesIdEditRoute
  '/pipelines/$id/': typeof PipelinesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pipelines/create': typeof PipelinesCreateRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/sinks': typeof SinksIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/pipelines/$id/edit': typeof PipelinesIdEditRoute
  '/pipelines/$id': typeof PipelinesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/pipelines/create': typeof PipelinesCreateRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/sinks/': typeof SinksIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/pipelines/$id/edit': typeof PipelinesIdEditRoute
  '/pipelines/$id/': typeof PipelinesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/config'
    | '/dashboard'
    | '/login'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pipelines/create'
    | '/pipelines/'
    | '/sinks/'
    | '/sources/'
    | '/pipelines/$id/edit'
    | '/pipelines/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/config'
    | '/dashboard'
    | '/login'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pipelines/create'
    | '/pipelines'
    | '/sinks'
    | '/sources'
    | '/pipelines/$id/edit'
    | '/pipelines/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/config'
    | '/dashboard'
    | '/login'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/pipelines/create'
    | '/pipelines/'
    | '/sinks/'
    | '/sources/'
    | '/pipelines/$id/edit'
    | '/pipelines/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfigRoute: typeof ConfigRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PipelinesCreateRoute: typeof PipelinesCreateRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  SinksIndexRoute: typeof SinksIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  PipelinesIdEditRoute: typeof PipelinesIdEditRoute
  PipelinesIdIndexRoute: typeof PipelinesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinks/': {
      id: '/sinks/'
      path: '/sinks'
      fullPath: '/sinks/'
      preLoaderRoute: typeof SinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/create': {
      id: '/pipelines/create'
      path: '/pipelines/create'
      fullPath: '/pipelines/create'
      preLoaderRoute: typeof PipelinesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$id/': {
      id: '/pipelines/$id/'
      path: '/pipelines/$id'
      fullPath: '/pipelines/$id/'
      preLoaderRoute: typeof PipelinesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$id/edit': {
      id: '/pipelines/$id/edit'
      path: '/pipelines/$id/edit'
      fullPath: '/pipelines/$id/edit'
      preLoaderRoute: typeof PipelinesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfigRoute: ConfigRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PipelinesCreateRoute: PipelinesCreateRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  SinksIndexRoute: SinksIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  PipelinesIdEditRoute: PipelinesIdEditRoute,
  PipelinesIdIndexRoute: PipelinesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
